### ISSUE TITLE
Survey

### ISSUE THREAD

**Issue by hwhelchel** [kindlyops/chirpyhire#1]
As a home care recruiter, I would like to be able to survey leads so that I can hire the best candidates for my agency.

- [ ] Surveyor welcomes the Person
- [ ] Surveyor asks the questions
- [ ] Surveyor gets the next question from the Survey
- [ ] Survey has Questions (experience, skin test, availability, transportation, zip code, certification, CPR / 1st Aid)
- [ ] Surveyor uses the Survey (uses the Questions) to determine the validity of an answer
- [ ] If answer to a question is valid or invalid, the Surveyor uses the Survey (and Question) to determine the appropriate response
- [ ] Surveyor saves each outbound and inbound message
- [ ] Surveyor creates or updates the person's candidacy and updates the question the person is on when valid answer
- [ ] Surveyor thanks the respondent in a standard way at end of survey
