### ISSUE TITLE
ChirpyHire Teams - Part 1

### ISSUE THREAD

**Issue by hwhelchel** [kindlyops/chirpyhire#304]
### Part 1

- [x] Create Teams and Memberships
- [x] Tie contacts, accounts, locations, and recruiting ads to teams
- [x] Create team and team location when creating an account
- [x] When contacts text in, set team on them if it isn't set
- [x] When a user accepts an invitation, add them to the initial team
- [x] Seed teams and connect existing contacts, accounts, locations, and recruiting ads to the team
